#!/bin/bash

callMM () {
  CR="\r\n"
  input=$1
  if [[ $input = *";"* ]]; then
    oldIFS=$IFS
    IFS=';'
    array=($input)
    IFS=$oldIFS
    for element in "${array[@]}"
    do
      A+=$(mmcli -m 0 --command="+$element")
      A+=$CR
    done
  else
    A=$(mmcli -m 0 --command="+$1")
    A+=$CR
  fi
  echo ${A} | sed 's/response: //g'
}


while true; do
    # Run AT+CGMM to get the modem model
    echo -en $(callMM "CGMM")  > /tmp/modemmodel.txt
    sleep 2

    #  Run AT+CGCONTRDP once then proceed to while loop
    echo -en $(callMM "CGCONTRDP=1") > /tmp/apn.txt
    sleep 2

    # Run AT+QUIMSLOT? to get the current sim slot
    echo -en $(callMM "QUIMSLOT?") > /tmp/simslot.txt
    sleep 2

    # Send request to modem and wait 3 seconds for data
    echo -en $(callMM "QSPN;CEREG=2;CEREG?;CEREG=0;C5GREG=2;C5GREG?;C5GREG=0;CSQ;QENG=\"servingcell\";QRSRP;QCAINFO;QNWPREFCFG=\"mode_pref\";QTEMP") > /tmp/modemstatus.txt
    if [ $? -eq 0 ]

    then
        # Parse
        if [ -f /tmp/modemstatus.txt ]
        then
    	      /usrdata/simpleadmin/scripts/modemstatus_parse.sh
        fi
    fi
    sleep 25  # Add a sleep to avoid CPU overload
done
